name       : qol-assist
version    : 0.4.0
release    : 13
source     :
    - https://github.com/solus-project/qol-assist/releases/download/v0.4.0/qol-assist-0.4.0.tar.xz : 4f42b984a452d4f67393898fcf876de83ef2ac4ca566e74e2caedd0516e7e96b
license    : GPL-2.0
component  : system.base
summary    : QoL Assistance
description: |
    QoL Assist is a Solus tool to help rolling releases roll better over time,
    performing migratory functions automatically.
builddeps  :
    - pkgconfig(systemd)
    - musl-devel
optimize   :
    - size
    - lto
setup      : |
    CC=musl-gcc LD_PRELOAD='' %meson_configure -Dwith-static-binary=true
build      : |
    LD_PRELOAD='' %meson_build
install    : |
    LD_PRELOAD='' %meson_install
    install -D -d -m 00755 $installdir/usr/lib/systemd/system/sysinit.target.wants
    ln -sv ../qol-assist-migration.service $installdir/usr/lib/systemd/system/sysinit.target.wants/.
