name       : qol-assist
version    : 0.3.0
release    : 10
source     :
    - https://github.com/solus-project/qol-assist/releases/download/v0.3.0/qol-assist-0.3.0.tar.xz : 12ea8531eff762f9bf6c2910e0ff0adb255996b9cb26ab5e1d7d5d85622d8ccb
license    : GPL-2.0
component  : system.base
summary    : QoL Assistance
description: |
    QoL Assist is a Solus tool to help rolling releases roll better over time,
    performing migratory functions automatically.
builddeps  :
    - pkgconfig(systemd)
    - musl-devel
optimize   :
    - size
    - lto
setup      : |
    CC=musl-gcc LD_PRELOAD='' %meson_configure -Dwith-static-binary=true
build      : |
    LD_PRELOAD='' %meson_build
install    : |
    LD_PRELOAD='' %meson_install
    install -D -d -m 00755 $installdir/usr/lib/systemd/system/sysinit.target.wants
    ln -sv ../qol-assist-migration.service $installdir/usr/lib/systemd/system/sysinit.target.wants/.
