name       : qol-assist
version    : 0.2.0
release    : 9
source     :
    - https://github.com/solus-project/qol-assist/releases/download/v0.2.0/qol-assist-0.2.0.tar.xz : 515c0f6d91659383aba610408101b49aaa01b3a27dfbb8f257e251a5bd0e5dd7
license    : GPL-2.0
component  : system.base
summary    : QoL Assistance
description: |
    QoL Assist is a Solus tool to help rolling releases roll better over time,
    performing migratory functions automatically.
builddeps  :
    - pkgconfig(systemd)
    - musl-devel
optimize   :
    - size
    - lto
setup      : |
    %apply_patches
    CC=musl-gcc LD_PRELOAD='' %meson_configure -Dwith-static-binary=true
build      : |
    LD_PRELOAD='' %meson_build
install    : |
    LD_PRELOAD='' %meson_install
    install -D -d -m 00755 $installdir/usr/lib/systemd/system/sysinit.target.wants
    ln -sv ../qol-assist-migration.service $installdir/usr/lib/systemd/system/sysinit.target.wants/.
