name       : qol-assist
version    : 0.0.2
release    : 6
source     :
    - https://github.com/solus-project/qol-assist/releases/download/v0.0.2/qol-assist-0.0.2.tar.xz : 4ce98d67d2ba785e97a307b711f46afe1732f08ca388cc29766a6dd1c2ebdb28
license    : GPL-2.0
component  : system.base
summary    : QoL Assistance
description: |
    QoL Assist is a Solus tool to help rolling releases roll better over time,
    performing migratory functions automatically.
builddeps  :
    - pkgconfig(systemd)
    - musl-devel
optimize   :
    - size
setup      : |
    %apply_patches
    CC=musl-gcc LD_PRELOAD='' %meson_configure -Dwith-static-binary=true
build      : |
    LD_PRELOAD='' %meson_build
install    : |
    LD_PRELOAD='' %meson_install
    install -D -d -m 00755 $installdir/usr/lib/systemd/system/sysinit.target.wants
    ln -sv ../qol-assist-migration.service $installdir/usr/lib/systemd/system/sysinit.target.wants/.
