name       : qol-assist
version    : 0.9.0
release    : 16
source     :
    - https://github.com/getsolus/qol-assist/releases/download/v0.9.0/qol-assist-v0.9.0.tar.gz : c62a112ad5e9511ec2c8e51bf0cb6f7896092114be92b0069203b4ff8a6547c4
license    : Apache-2.0
component  : system.base
summary    : QoL Assistance
description: |
    QoL Assist is a Solus tool to help rolling releases roll better over time, performing migratory functions automatically.
builddeps  :
    - pkgconfig(systemd)
    - golang
    - scdoc # man
setup      : |
    %patch -p1 < $pkgfiles/0001-Makefile-Fix-typo-in-USRDIR.patch
    %patch -p1 < $pkgfiles/0001-core-context-Exclude-root-from-admin-users.patch
build      : |
    %make PREFIX=/usr BINDIR=/usr/sbin
install    : |
    %make_install \
        PREFIX=/usr \
        SYSTEMDUNITDIR=$installdir/usr/lib/systemd/system \
        BINDIR=$installdir/usr/sbin \
        MANDIR=$installdir/usr/share/man/man1

    # Install all legacy triggers (just in case tm) as well as for testing
    for i in $pkgfiles/*.toml; do
        install -Dm00644 ${i} $installdir/usr/share/defaults/qol-assist.d/`basename ${i}`
    done

    install -D -d -m 00755 $installdir/usr/lib/systemd/system/sysinit.target.wants
    ln -sv ../qol-assist-migration.service $installdir/usr/lib/systemd/system/sysinit.target.wants/.
