name       : qol-assist
version    : 0.0.1
release    : 2
source     :
    - https://github.com/solus-project/qol-assist/releases/download/v0.0.1/qol-assist-0.0.1.tar.xz : 7e1af25743a55650715b49052c28f8f3a40740ff6eaae1deece2caebb9f99d07
license    : GPL-2.0
component  : system.base
summary    : QoL Assistance
description: |
    QoL Assist is a Solus tool to help rolling releases roll better over time,
    performing migratory functions automatically.
builddeps  :
    - pkgconfig(systemd)
rundeps    :
    - kernel-glue
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-broken-installation-of-systemd-unit.patch
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
    install -D -d -m 00755 $installdir/usr/lib/systemd/system/sysinit.target.wants
    ln -sv ../qol-assist-migration.service $installdir/usr/lib/systemd/system/sysinit.target.wants/.
