name       : qol-assist
version    : 0.1.0
release    : 7
source     :
    - https://github.com/solus-project/qol-assist/releases/download/v0.1.0/qol-assist-0.1.0.tar.xz : 537291030d2cbe69e6ff87dc582060dea193841237aa98793e534c3b26224510
license    : GPL-2.0
component  : system.base
summary    : QoL Assistance
description: |
    QoL Assist is a Solus tool to help rolling releases roll better over time,
    performing migratory functions automatically.
builddeps  :
    - pkgconfig(systemd)
    - musl-devel
optimize   :
    - size
    - lto
setup      : |
    CC=musl-gcc LD_PRELOAD='' %meson_configure -Dwith-static-binary=true
build      : |
    LD_PRELOAD='' %meson_build
install    : |
    LD_PRELOAD='' %meson_install
    install -D -d -m 00755 $installdir/usr/lib/systemd/system/sysinit.target.wants
    ln -sv ../qol-assist-migration.service $installdir/usr/lib/systemd/system/sysinit.target.wants/.
